defaults:
    run: 
        shell: bash
        working-directory: .
on: push
jobs:
    example-job:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13' 
        - uses: actions/cache@v3
          with: 
              run: pip install -r requirements.txt
              key: ${{ runner.os }}-requirements
        - run: chmod +x ./create_exe.sh
        - run: ./create_exe.sh
        - run: cp -r assets dist/
        - run: mkdir dist/logs
        - run: touch dist/logs/logs.txt
        # - run: zip -r game.zip dist
        - uses: actions/upload-artifact@v4
          with:
              path: dist
