defaults:
    run: 
        shell: bash
        working-directory: .
on: push
jobs:
    example-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: ./create_exe.sh
